[global]
# Reduce anonymous enumeration
restrict anonymous = 2

# Disable NetBIOS; SMB only on 445
disable netbios = yes
smb ports = 445

# Force SMB encryption
smb encrypt = required

# Disable printing/spoolss on a DC
printcap name = /dev/null
load printers = no
disable spoolss = yes
printing = bsd

# Kill NTLMv1
ntlm auth = mschapv2-and-ntlmv2-only

# Constrain RPC dynamic ports (then firewall only this range)
rpc server dynamic port range = 50000-55000

# LDAP TLS (point to internal certs fixed by init.sh)
#tls enabled  = yes
tls keyfile  = /etc/samba/tls/privkey.pem
tls certfile = /etc/samba/tls/fullchain.pem
tls cafile   = /etc/samba/tls/chain.pem
